package com.example.compose
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF00677C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB1ECFF)
val onPrimaryContainerLight = Color(0xFF004E5E)
val secondaryLight = Color(0xFF4B626A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCEE7F0)
val onSecondaryContainerLight = Color(0xFF344A51)
val tertiaryLight = Color(0xFF585C7E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDFE0FF)
val onTertiaryContainerLight = Color(0xFF404565)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FAFD)
val onBackgroundLight = Color(0xFF171C1E)
val surfaceLight = Color(0xFFF5FAFD)
val onSurfaceLight = Color(0xFF171C1E)
val surfaceVariantLight = Color(0xFFDBE4E8)
val onSurfaceVariantLight = Color(0xFF40484B)
val outlineLight = Color(0xFF70787C)
val outlineVariantLight = Color(0xFFBFC8CC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3133)
val inverseOnSurfaceLight = Color(0xFFECF1F4)
val inversePrimaryLight = Color(0xFF86D1E9)
val surfaceDimLight = Color(0xFFD6DBDD)
val surfaceBrightLight = Color(0xFFF5FAFD)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF4F7)
val surfaceContainerLight = Color(0xFFEAEFF1)
val surfaceContainerHighLight = Color(0xFFE4E9EB)
val surfaceContainerHighestLight = Color(0xFFDEE3E6)



val primaryDark = Color(0xFF86D1E9)
val onPrimaryDark = Color(0xFF003642)
val primaryContainerDark = Color(0xFF004E5E)
val onPrimaryContainerDark = Color(0xFFB1ECFF)
val secondaryDark = Color(0xFFB2CAD3)
val onSecondaryDark = Color(0xFF1D343B)
val secondaryContainerDark = Color(0xFF344A51)
val onSecondaryContainerDark = Color(0xFFCEE7F0)
val tertiaryDark = Color(0xFFC1C4EB)
val onTertiaryDark = Color(0xFF2A2E4D)
val tertiaryContainerDark = Color(0xFF404565)
val onTertiaryContainerDark = Color(0xFFDFE0FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1416)
val onBackgroundDark = Color(0xFFDEE3E6)
val surfaceDark = Color(0xFF0F1416)
val onSurfaceDark = Color(0xFFDEE3E6)
val surfaceVariantDark = Color(0xFF40484B)
val onSurfaceVariantDark = Color(0xFFBFC8CC)
val outlineDark = Color(0xFF899296)
val outlineVariantDark = Color(0xFF40484B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E6)
val inverseOnSurfaceDark = Color(0xFF2C3133)
val inversePrimaryDark = Color(0xFF00677C)
val surfaceDimDark = Color(0xFF0F1416)
val surfaceBrightDark = Color(0xFF343A3C)
val surfaceContainerLowestDark = Color(0xFF090F11)
val surfaceContainerLowDark = Color(0xFF171C1E)
val surfaceContainerDark = Color(0xFF1B2022)
val surfaceContainerHighDark = Color(0xFF252B2D)
val surfaceContainerHighestDark = Color(0xFF303638)








